import type { Stamp } from './types';

export const stampData: Stamp[] = [
  // ═══ Basic Rooms ═══
  // Convention: north/south walls = 2 rows (#), side walls = 1 col (#)
  // Row layout: 2 wall rows (top) → floor → 2 wall rows (bottom)
  // Side walls: 1 column each side
  { name: 'Small Square Room', size: '9x8', tags: ['basic', 'small', 'empty'],
    grid: [
      '#########',
      '#########',
      '#.......#',
      '#.......#',
      '#.......#',
      '#.......#',
      '#########',
      '#########',
    ].join('\n'), difficulty: 0, theme: 'stone' },

  { name: 'Large Hall', size: '15x11', tags: ['basic', 'large', 'hall'],
    grid: [
      '###############',
      '###############',
      '#.............#',
      '#.............#',
      '#.............#',
      '#.............#',
      '#.............#',
      '#.............#',
      '#.............#',
      '###############',
      '###############',
    ].join('\n'), difficulty: 0, theme: 'stone' },

  // ═══ Treasure Rooms ═══
  { name: 'Treasure Room with Pillars', size: '11x10', tags: ['treasure', 'combat', 'pillars'],
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#.P.....P.#',
      '#.........#',
      '#....C....#',
      '#.........#',
      '#.P.....P.#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  { name: 'Vault Room', size: '11x10', tags: ['treasure', 'vault', 'secure'],
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#.#######.#',
      '#.##CCC#.#',
      '#.###D##.#',
      '#.........#',
      '#.........#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 3, theme: 'stone' },

  { name: 'Corner Treasure Cache', size: '9x8', tags: ['treasure', 'small', 'corner'],
    grid: [
      '#########',
      '#########',
      '#.......#',
      '#.......#',
      '#.......#',
      '#....##C#',
      '#########',
      '#########',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  // ═══ Combat Arenas ═══
  { name: 'Small Arena', size: '11x10', tags: ['arena', 'combat', 'boss'],
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#.........#',
      '#....@....#',
      '#.........#',
      '#.........#',
      '#.........#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  { name: 'Pillared Arena', size: '13x12', tags: ['arena', 'pillars', 'tactical'],
    grid: [
      '#############',
      '#############',
      '#...........#',
      '#.P.......P.#',
      '#...........#',
      '#...........#',
      '#.....@.....#',
      '#...........#',
      '#...........#',
      '#.P.......P.#',
      '#############',
      '#############',
    ].join('\n'), difficulty: 3, theme: 'stone' },

  // ═══ Ambush & Trap Rooms ═══
  { name: 'Flanking Ambush', size: '13x10', tags: ['ambush', 'tactical', 'dangerous'],
    grid: [
      '#############',
      '#############',
      '#...........#',
      '#@##.....##@#',
      '#.##.....##.#',
      '#@##.....##@#',
      '#...........#',
      '#...........#',
      '#############',
      '#############',
    ].join('\n'), difficulty: 3, theme: 'stone' },

  { name: 'Spike Corridor', size: '11x6', tags: ['trap', 'corridor', 'hazard'], category: 'corridor',
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#..TTTTT..#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  { name: 'Treasure Trap', size: '9x8', tags: ['treasure', 'trap', 'puzzle'],
    grid: [
      '#########',
      '#########',
      '#.......#',
      '#..TTT..#',
      '#..TCT..#',
      '#..TTT..#',
      '#########',
      '#########',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  { name: 'Pit Room', size: '11x10', tags: ['hazard', 'pit', 'parkour'],
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#..~~.~~..#',
      '#.........#',
      '#..~~.~~..#',
      '#.........#',
      '#..~~.~~..#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  // ═══ Shrine & Rest Rooms ═══
  { name: 'Small Shrine', size: '9x8', tags: ['shrine', 'reward', 'rest'],
    grid: [
      '#########',
      '#########',
      '#.......#',
      '#...P...#',
      '#.......#',
      '#...S...#',
      '#########',
      '#########',
    ].join('\n'), difficulty: 0, theme: 'stone' },

  { name: 'Healing Fountain', size: '11x10', tags: ['shrine', 'fountain', 'healing'],
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#.........#',
      '#....W....#',
      '#...WWW...#',
      '#....W....#',
      '#.........#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 0, theme: 'water' },

  { name: 'Meditation Chamber', size: '11x10', tags: ['shrine', 'peaceful', 'rest'],
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#.P.....P.#',
      '#.........#',
      '#....S....#',
      '#.........#',
      '#.P.....P.#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 0, theme: 'stone' },

  // ═══ L-Shaped & Irregular Rooms ═══
  // These use void (space) for the non-room area
  // Irregular shapes need extra care: 2-row walls on every north-facing edge
  { name: 'L-Shaped Room', size: '13x12', tags: ['irregular', 'L-shape', 'tactical'],
    grid: [
      '########     ',
      '########     ',
      '#......#     ',
      '#......#     ',
      '#......######',
      '#......######',
      '#............#',
      '#............#',
      '#............#',
      '#............#',
      '##############',
      '##############',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  { name: 'T-Junction Room', size: '13x14', tags: ['irregular', 'T-shape', 'junction'],
    grid: [
      '     ###     ',
      '     ###     ',
      '     #.#     ',
      '     #.#     ',
      '#############',
      '#############',
      '#...........#',
      '#...........#',
      '#############',
      '#############',
      '     #.#     ',
      '     #.#     ',
      '     ###     ',
      '     ###     ',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  { name: 'Cross Room', size: '13x14', tags: ['irregular', 'cross', 'junction'],
    grid: [
      '     ###     ',
      '     ###     ',
      '     #.#     ',
      '     #.#     ',
      '#############',
      '#############',
      '#.....C.....#',
      '#...........#',
      '#############',
      '#############',
      '     #.#     ',
      '     #.#     ',
      '     ###     ',
      '     ###     ',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  // ═══ Decorated Rooms ═══
  { name: 'Columned Hall', size: '15x11', tags: ['decorated', 'hall', 'pillars'],
    grid: [
      '###############',
      '###############',
      '#.............#',
      '#.P.P.P.P.P.P.#',
      '#.............#',
      '#.............#',
      '#.............#',
      '#.P.P.P.P.P.P.#',
      '#.............#',
      '###############',
      '###############',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  { name: 'Storage Room', size: '11x10', tags: ['storage', 'crates', 'loot'],
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#.B.B.B.B.#',
      '#.........#',
      '#.B.B.B.B.#',
      '#.........#',
      '#.B.B.B.B.#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  { name: 'Guard Barracks', size: '13x10', tags: ['barracks', 'guards', 'combat'],
    grid: [
      '#############',
      '#############',
      '#...........#',
      '#.@.......@.#',
      '#...........#',
      '#...........#',
      '#.@.......@.#',
      '#...........#',
      '#############',
      '#############',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  { name: 'Library', size: '11x10', tags: ['library', 'loot', 'knowledge'],
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#..#####..#',
      '#..#...#..#',
      '#..#.C.#..#',
      '#..##D##..#',
      '#.........#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  { name: 'Prison Cells', size: '13x10', tags: ['prison', 'cells', 'rescue'],
    grid: [
      '#############',
      '#############',
      '#.##.##.##.##',
      '#...........#',
      '#.##.##.##.##',
      '#...........#',
      '#.##.##.##.##',
      '#...........#',
      '#############',
      '#############',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  // ═══ Boss Rooms ═══
  { name: 'Throne Room', size: '15x13', tags: ['boss', 'throne', 'large'],
    grid: [
      '###############',
      '###############',
      '#.............#',
      '#.P.........P.#',
      '#.............#',
      '#.............#',
      '#.............#',
      '#.............#',
      '#......@......#',
      '#.P.........P.#',
      '#.............#',
      '###############',
      '###############',
    ].join('\n'), difficulty: 4, theme: 'stone' },

  { name: 'Ritual Circle', size: '13x12', tags: ['boss', 'ritual', 'mystical'],
    grid: [
      '#############',
      '#############',
      '#...........#',
      '#..P.....P..#',
      '#...........#',
      '#.P...@...P.#',
      '#...........#',
      '#..P.....P..#',
      '#...........#',
      '#..P.....P..#',
      '#############',
      '#############',
    ].join('\n'), difficulty: 4, theme: 'mystical' },

  // ═══ Themed Rooms ═══
  { name: 'Flooded Room', size: '11x10', tags: ['water', 'hazard', 'environmental'],
    grid: [
      '###########',
      '###########',
      '#WWWWWWWWW#',
      '#W.......W#',
      '#W.......W#',
      '#W.......W#',
      '#W.......W#',
      '#WWWWWWWWW#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 2, theme: 'water' },

  { name: 'Garden Courtyard', size: '13x12', tags: ['garden', 'peaceful', 'outdoor'],
    grid: [
      '#############',
      '#############',
      '#...........#',
      '#.G.G.G.G.G.#',
      '#...........#',
      '#.G.......G.#',
      '#.....W.....#',
      '#.G.......G.#',
      '#...........#',
      '#.G.G.G.G.G.#',
      '#############',
      '#############',
    ].join('\n'), difficulty: 0, theme: 'grass' },

  { name: 'Crypt', size: '11x10', tags: ['crypt', 'undead', 'spooky'],
    grid: [
      '###########',
      '###########',
      '#.........#',
      '#.P..@..P.#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.P.....P.#',
      '###########',
      '###########',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  { name: 'Maze Fragment', size: '13x12', tags: ['maze', 'puzzle', 'complex'],
    grid: [
      '#############',
      '#############',
      '#.##.##.##.##',
      '#...........#',
      '####.####.###',
      '#...........#',
      '####.####.###',
      '#...........#',
      '#.##.##.##.##',
      '#...........#',
      '#############',
      '#############',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  // ═══ LARGE ROOMS ═══
  { name: 'Grand Throne Hall', size: '21x16', tags: ['boss', 'throne', 'large', 'pillars'],
    grid: [
      '#####################',
      '#####################',
      '#...................#',
      '#.P...............P.#',
      '#...................#',
      '#..P....P.P....P...#',
      '#...................#',
      '#...................#',
      '#........P.P.......#',
      '#...................#',
      '#...................#',
      '#..P....P.P....P...#',
      '#...................#',
      '#.P......@......P..#',
      '#####################',
      '#####################',
    ].join('\n'), difficulty: 4, theme: 'stone' },

  { name: 'Great Feast Hall', size: '19x16', tags: ['hall', 'large', 'social'],
    grid: [
      '###################',
      '###################',
      '#.................#',
      '#.P.............P.#',
      '#.................#',
      '#...BBBBBBBBB.....#',
      '#...B.......B.....#',
      '#...B.......B.....#',
      '#...B.......B.....#',
      '#...BBBBBBBBB.....#',
      '#.................#',
      '#.................#',
      '#.P.............P.#',
      '#.................#',
      '###################',
      '###################',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  { name: 'Cathedral', size: '17x22', tags: ['shrine', 'large', 'pillars', 'mystical'],
    grid: [
      '#################',
      '#################',
      '#...............#',
      '#.P...........P.#',
      '#...............#',
      '#.P...........P.#',
      '#...............#',
      '#.P...........P.#',
      '#...............#',
      '#.P...........P.#',
      '#...............#',
      '#.P...........P.#',
      '#...............#',
      '#.P...........P.#',
      '#...............#',
      '#.P...........P.#',
      '#...............#',
      '#.......S.......#',
      '#...............#',
      '#.......D.......#',
      '#################',
      '#################',
    ].join('\n'), difficulty: 0, theme: 'mystical' },

  { name: 'Underground Lake', size: '19x18', tags: ['water', 'large', 'environmental', 'cave'],
    grid: [
      '###################',
      '###################',
      '#.................#',
      '#..WWWWWWWWWWW....#',
      '#.WWWWWWWWWWWWW...#',
      '#.WWWWWWWWWWWWWW..#',
      '#.WWWWWWWWWWWWWW..#',
      '#..WWWWWWWWWWWWW..#',
      '#...WWWWWWWWWWW...#',
      '#....WWWWWWWWW....#',
      '#.....WWWWWWW.....#',
      '#......WWWWW......#',
      '#.................#',
      '#..P.........P....#',
      '#.................#',
      '#.................#',
      '###################',
      '###################',
    ].join('\n'), difficulty: 1, theme: 'water' },

  { name: 'Armory', size: '17x16', tags: ['loot', 'large', 'weapons', 'storage'],
    grid: [
      '#################',
      '#################',
      '#...............#',
      '#.B.B.B...B.B.B.#',
      '#...............#',
      '#.B.B.B...B.B.B.#',
      '#...............#',
      '#.B.B.B...B.B.B.#',
      '#...............#',
      '#...............#',
      '#.......C.......#',
      '#...............#',
      '#.P...........P.#',
      '#...............#',
      '#################',
      '#################',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  { name: 'Great Hall with Side Alcoves', size: '21x16', tags: ['hall', 'large', 'alcoves', 'tactical'],
    grid: [
      '#####################',
      '#####################',
      '#...................#',
      '#.P...............P.#',
      '##.##.........##.##.#',
      '#...#.........#...#.#',
      '#...#.........#...#.#',
      '##.##.........##.##.#',
      '#...................#',
      '#...B.........B.....#',
      '#...................#',
      '#.P...............P.#',
      '#...................#',
      '#.........D.........#',
      '#####################',
      '#####################',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  { name: 'Necromancer Lair', size: '17x18', tags: ['boss', 'large', 'undead', 'ritual'],
    grid: [
      '#################',
      '#################',
      '#...............#',
      '#..P.........P..#',
      '#...............#',
      '#....P.....P....#',
      '#...............#',
      '#......P.P......#',
      '#.......S.......#',
      '#......P.P......#',
      '#...............#',
      '#....P.....P....#',
      '#...............#',
      '#..P.........P..#',
      '#...............#',
      '#.......@.......#',
      '#################',
      '#################',
    ].join('\n'), difficulty: 4, theme: 'mystical' },

  { name: 'Flooded Crypt', size: '17x16', tags: ['water', 'large', 'undead', 'crypt'],
    grid: [
      '#################',
      '#################',
      '#WWWWWWWWWWWWWWW#',
      '#W.............W#',
      '#W..P...C...P..W#',
      '#W.............W#',
      '#WWWW.....WWWWW#',
      '#...............#',
      '#WWWW.....WWWWW#',
      '#W.............W#',
      '#W.............W#',
      '#W..P...@...P..W#',
      '#W.............W#',
      '#WWWWWWWWWWWWWWW#',
      '#################',
      '#################',
    ].join('\n'), difficulty: 3, theme: 'water' },

  { name: 'Garden Ruins', size: '19x18', tags: ['garden', 'large', 'outdoor', 'peaceful'],
    grid: [
      '###################',
      '###################',
      '#.................#',
      '#.GGG.........GGG.#',
      '#.GGG..P...P..GGG.#',
      '#.GGG.........GGG.#',
      '#.................#',
      '#....GGG...GGG....#',
      '#....GGG.W.GGG....#',
      '#....GGG...GGG....#',
      '#.................#',
      '#.GGG.........GGG.#',
      '#.GGG..P...P..GGG.#',
      '#.GGG.........GGG.#',
      '#.................#',
      '#.......D.........#',
      '###################',
      '###################',
    ].join('\n'), difficulty: 0, theme: 'grass' },

  { name: 'Prison Block', size: '19x16', tags: ['prison', 'large', 'cells', 'rescue'],
    grid: [
      '###################',
      '###################',
      '#.................#',
      '#.####.####.####.##',
      '#.#..#.#..#.#..#.##',
      '#.#D.#.#D.#.#D.#.##',
      '#.................#',
      '#.................#',
      '#.................#',
      '#.#D.#.#D.#.#D.#.##',
      '#.#..#.#..#.#..#.##',
      '#.####.####.####.##',
      '#.................#',
      '#.................#',
      '###################',
      '###################',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  // ═══ INTERIOR SUB-STAMPS ═══
  { name: 'Pillar Grid 3x3', size: '5x5', tags: ['interior', 'pillars', 'tactical'],
    grid: [
      'P...P',
      '.....',
      '..P..',
      '.....',
      'P...P',
    ].join('\n'), difficulty: 0, theme: 'stone' },

  { name: 'Campfire Circle', size: '5x5', tags: ['interior', 'rest', 'camp'],
    grid: [
      '..B..',
      '.B.B.',
      '..S..',
      '.B.B.',
      '..B..',
    ].join('\n'), difficulty: 0, theme: 'stone' },

  { name: 'Altar Setup', size: '5x5', tags: ['interior', 'shrine', 'mystical'],
    grid: [
      '..P..',
      '.....',
      'P.S.P',
      '.....',
      '..P..',
    ].join('\n'), difficulty: 0, theme: 'mystical' },

  { name: 'Crate Storage Cluster', size: '5x5', tags: ['interior', 'storage', 'loot'],
    grid: [
      'BBB..',
      'BBB..',
      'BBB..',
      '.....',
      '.....',
    ].join('\n'), difficulty: 0, theme: 'stone' },

  { name: 'Chest Alcove', size: '5x4', tags: ['interior', 'treasure', 'alcove'],
    grid: [
      '#####',
      '#####',
      '#.C.#',
      '##.##',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  { name: 'Water Pool', size: '5x5', tags: ['interior', 'water', 'decoration'],
    grid: [
      '.WWW.',
      'WWWWW',
      'WWWWW',
      'WWWWW',
      '.WWW.',
    ].join('\n'), difficulty: 0, theme: 'water' },

  { name: 'Spike Trap Line', size: '7x3', tags: ['interior', 'trap', 'corridor'], category: 'corridor',
    grid: [
      '.......',
      '.TTTTT.',
      '.......',
    ].join('\n'), difficulty: 1, theme: 'stone' },

  { name: 'Guard Post', size: '5x5', tags: ['interior', 'combat', 'patrol'],
    grid: [
      '.....',
      '.@.@.',
      '.....',
      '..B..',
      '.....',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  { name: 'Pillar Corridor', size: '3x9', tags: ['interior', 'corridor', 'pillars'], category: 'corridor',
    grid: [
      'P.P',
      '...',
      'P.P',
      '...',
      'P.P',
      '...',
      'P.P',
      '...',
      'P.P',
    ].join('\n'), difficulty: 0, theme: 'stone' },

  { name: 'Ritual Circle', size: '7x7', tags: ['interior', 'mystical', 'ritual'],
    grid: [
      '..P.P..',
      '.......',
      'P.....P',
      '...S...',
      'P.....P',
      '.......',
      '..P.P..',
    ].join('\n'), difficulty: 0, theme: 'mystical' },

  { name: 'Pit Hazard Zone', size: '5x5', tags: ['interior', 'hazard', 'pit'],
    grid: [
      '.~~~.',
      '~...~',
      '~...~',
      '~...~',
      '.~~~.',
    ].join('\n'), difficulty: 2, theme: 'stone' },

  { name: 'Garden Patch', size: '5x5', tags: ['interior', 'garden', 'decoration'],
    grid: [
      'GGGGG',
      'G...G',
      'G.W.G',
      'G...G',
      'GGGGG',
    ].join('\n'), difficulty: 0, theme: 'grass' },
];
